src/Iauq.Information/Areas/Administration/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Iauq.Core.Domain;
using Iauq.Core.Utilities;
using Iauq.Data;
using Iauq.Data.Services;
using Iauq.Information.App_GlobalResources;
using Iauq.Information.Helpers;
using Iauq.Information.LogProviders;
using MvcContrib.Pagination;

namespace Iauq.Information.Areas.Administration.Controllers
{
    [CustomAuthorize(Roles = "Administrators, Moderators, Editors")]
    public class ContentsController : AdministrationControllerBase
    {
        private readonly ICategoryService _categoryService;
        private readonly IContentService _contentService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHelper _webHelper;

        public ContentsController(IUnitOfWork unitOfWork, IContentService contentService,
                                  ICategoryService categoryService, IWebHelper webHelper)
        {
            _unitOfWork = unitOfWork;
            _contentService = contentService;
            _categoryService = categoryService;
            _webHelper = webHelper;
        }


        [HttpGet]
        public ActionResult List(string contentType = null, int page = 1, int recordPerPage = Constants.RecordPerPage)
        {
            IPagination<Content> results;

            if (contentType == null)
            {
                if (page < 1)
                    return RedirectToActionPermanent("List", new {page = 1});

                IQueryable<Content> query = _contentService.GetAllContents();

                ExcludeNotRealatedRecords(ref query);

                query = query.OrderBy(c => c.Id).AsQueryable();

                results = new LazyPagination<Content>(query, page,
                                                      recordPerPage);

                if (!results.Any() && page != 1)
                    return RedirectToActionPermanent("List", new {page = 1});
            }
            else
            {
                ContentType type;

                if (!ExtractContentType(contentType, out type))
                    return NotFoundView();

                if (page < 1)
                    return RedirectToActionPermanent("List", new {page = 1, contentType = type});

                IQueryable<Content> query = _contentService.GetAllContentsByTypes(new[] {type});

                ExcludeNotRealatedRecords(ref query);

                query = query.OrderBy(c => c.Id).AsQueryable();

                results =
                    new LazyPagination<Content>(query,
                                                page,
                                                recordPerPage);

                if (!results.Any() && page != 1)
                    return RedirectToActionPermanent("List", new {page = 1, contentType = type});

                ViewBag.ContentType = type;
            }

            ViewBag.RecordPerPage = recordPerPage;

            return ViewOrPartialView(results);
        }

        private bool UserIsUnlimited()
        {
            User user = _webHelper.GetCurrentUser(ControllerContext.HttpContext);

            if (_webHelper.IsInRole(user, "Administrators") || _webHelper.IsInRole(user, "Moderators"))
                return true;

            return false;
        }

        private void ExcludeNotRealatedRecords(ref IQueryable<Content> query)
        {
            if (UserIsUnlimited())
                return;

            List<int> userCategories = GetUserCategories().Select(c => c.Id).ToList();

            query = from contents in query
                    where
                        userCategories.Contains(contents.CategoryId ?? -1) &&
                        contents.TypeInt != (short) ContentType.Menu
                    select contents;
        }

        private bool UserIsAllowedToCrud(Content content)
        {
            if (UserIsUnlimited())
                return true;

            if (content.TypeInt == (short) ContentType.Menu)
                return false;

            if (content.Id == 0)
                return true;

            List<int> userCategories = GetUserCategories().Select(c => c.Id).ToList();

            return userCategories.Contains(content.CategoryId ?? -1);
        }

        [HttpGet]
        public ActionResult Create(string contentType)
        {
            var content = new Content();

            ContentType type;

            if (!ExtractContentType(contentType, out type))
                return NotFoundView();

            ViewBag.Type = type;
            content.Type = type;

            ViewBag.UserIsUnlimited = UserIsUnlimited();

            if (ViewBag.UserIsUnlimited)
            {
                ViewBag.Categories =
                    _categoryService.GetAllCategories().OrderBy(c => c.ParentId.HasValue ? c.Parent.Title : c.Title).
                        ToList();

                ViewBag.Parents =
                    _contentService.GetAllContentsByTypes(new[] {ContentType.Menu, ContentType.Pages, ContentType.Links})
                        .OrderBy(c => c.ParentId.HasValue ? c.Parent.Title : c.Title).ToList();
            }
            else
            {
                ViewBag.Categories = GetUserCategories();

                ViewBag.Parents = GetParentsBasedOnUserCategories();
            }

            if (!UserIsAllowedToCrud(content))
                return AccessDeniedView();

            return ViewOrPartialView(content);
        }

        private IEnumerable<Category> GetUserCategories()
        {
            User user = _webHelper.GetCurrentUser(ControllerContext.HttpContext);

            List<Role> roles = user.Roles.ToList();

            List<int> categoryIds = roles.Where(r => r.Category != null).Select(r => r.Category.Id).ToList();

            return (from categories in _categoryService.GetAllCategories()
                    where categoryIds.Contains(categories.Id) || (categories.Parent != null &&
                                                                  categoryIds.Contains((int) categories.ParentId))
                    orderby categories.ParentId.HasValue ? categories.Parent.Title : categories.Title
                    select categories).ToList();
        }

        private bool ExtractContentType(string contentType, out ContentType type)
        {
            switch ((contentType ?? string.Empty).ToLowerInvariant())
            {
                case "news":
                    type = ContentType.News;
                    return true;
                case "event":
                    type = ContentType.Events;
                    return true;
                case "calendar":
                    type = ContentType.Calendars;
                    return true;
                case "page":
                    type = ContentType.Pages;
                    return true;
                case "link":
                    type = ContentType.Links;
                    return true;
                case "menu":
                    type = ContentType.Menu;
                    return true;
            }

            type = ContentType.News;
            return false;
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string contentType, Content content)
        {
            ContentType type;

            if (!ExtractContentType(contentType, out type))
                return NotFoundView();

            ViewBag.Type = type;

            ViewBag.UserIsUnlimited = UserIsUnlimited();

            if (!ModelState.IsValid)
            {
                if (ViewBag.UserIsUnlimited)
                {
                    ViewBag.Categories =
                        _categoryService.GetAllCategories().OrderBy(c => c.ParentId.HasValue ? c.Parent.Title : c.Title)
                            .ToList();

                    ViewBag.Parents =
                        _contentService.GetAllContentsByTypes(new[]
                                                                  {
                                                                      ContentType.Menu, ContentType.Pages,
                                                                      ContentType.Links
                                                                  }).OrderBy(
                                                                      c =>
                                                                      c.ParentId.HasValue ? c.Parent.Title : c.Title).
                            ToList();
                }
                else
                {
                    ViewBag.Categories = GetUserCategories();

                    ViewBag.Parents = GetParentsBasedOnUserCategories();
                }

                ModelState.AddModelError("",
                                         ValidationResources.InvalidState);

                return ViewOrPartialView(content);
            }

            content.Type = type;
            content.PublishDateTicks = DateTime.Now.Ticks;
            content.Author = _webHelper.GetCurrentUser(ControllerContext.HttpContext);
            content.IsPublished = true;

            if (content.Metadata == null)
                content.Metadata = new SeoMetadata();

            if (!string.IsNullOrEmpty(content.Metadata.SeoSlug))
                content.Metadata.SeoSlug = ValidateSlug(content.Metadata.SeoSlug);
            else
            {
                content.Metadata.SeoSlug = ValidateSlug(content.Title);
            }

            if (!string.IsNullOrEmpty(content.Tags))
                content.Tags = content.Tags.Trim(new[] {',', ';', '،'}).Trim();

            if (!UserIsAllowedToCrud(content))
                return AccessDeniedView();

            _contentService.SaveContent(content);

            bool isSaved;

            try
            {
                if (content.Metadata == null)
                    content.Metadata = new SeoMetadata();

src/Iauq.Information/Areas/Administration/Views/Contents/Create.cshtml
@using Iauq.Web.Mvc.UI
@model Iauq.Core.Domain.Content

@{
    ViewBag.Title = "پنل مدیریت - محتوا - ثبت محتوای جدید";
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("محتوا", "List", "Contents", new { page = 1 }, null));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("ثبت محتوای جدید", "Create", "Contents"));
}

<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr />
        @using (Html.BeginForm("Create", "Contents", FormMethod.Post, new {@class = "form-horizontal"}))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                @{ Html.RenderPartial("_NewOrUpdate", Model); }
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">ثبت</button>
                    @Html.ActionLink("برگشت", "List", new{page=1}, new {@class = "btn"})
                </div>
            </fieldset>
        }
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/Contents/Edit.cshtml
@using Iauq.Web.Mvc.UI
@model Iauq.Core.Domain.Content

@{
    ViewBag.Title = string.Format("پنل مدیریت - محتوا - ویرایش محتوا: {0}", Model.Title);
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("محتوا", "List", "Contents", new { page = 1 }, null));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink(string.Format("ویرایش محتوا: {0}", Model.Title), "Edit", "Contents", new { Model.Id }));
}

<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr />
        @using (Html.BeginForm("Edit", "Contents", new {Model.Id}, FormMethod.Post, new {@class = "form-horizontal"}))
        {
            <input type="hidden" name="id" value="@Model.Id" />
            @Html.ValidationSummary(true)
            <fieldset>
                @{ Html.RenderPartial("_NewOrUpdate", Model); }
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">بروز رسانی</button>
                    @Html.ActionLink("برگشت", "List", new { page = 1 }, new { @class = "btn" })
                </div>
            </fieldset>
        }
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/Contents/List.cshtml
@using Iauq.Core.Domain
@using Iauq.Core.Extensions
@using MvcContrib.Pagination
@using Iauq.Information.App_GlobalResources
@using Iauq.Information.Helpers
@using Iauq.Web.Mvc.UI
@model IEnumerable<Iauq.Core.Domain.Content>
@{
    ViewBag.Title = "پنل مدیریت - محتوا";
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("محتوا", "List", "Contents", new {page = 1}, null));

    dynamic hasType = ViewBag.ContentType != null;
    ContentType type = ContentType.News;
    int recordPerPage = ViewBag.RecordPerPage ?? Constants.RecordPerPage;
    if (hasType)
    {
        type = (ContentType) ViewBag.ContentType;
    }
}
<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <div class="btn-toolbar ignore-heading pull-left">
            <div class="btn-group">
                <button class="btn btn-warning dropdown-toggle" data-toggle="dropdown">@(" [" + recordPerPage + "] ")... <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li>@Html.RouteLink("همه", "AdministrationList", new { Controller = "Contents", page = ((IPagination)Model).PageNumber })</li>
                    <li>@Html.ActionLink("10", "List", new { Controller = "Contents", page = ((IPagination)Model).PageNumber, recordPerPage = 10 })</li>
                    <li>@Html.ActionLink("50", "List", new { Controller = "Contents", page = ((IPagination)Model).PageNumber, recordPerPage = 50 })</li>
                    <li>@Html.ActionLink("100", "List", new { Controller = "Contents", page = ((IPagination)Model).PageNumber, recordPerPage = 100 })</li>
                </ul>
            </div>    
            <div class="btn-group">
                <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">فیلتر بر اساس@(hasType?" ["+type.ToLocalizedString()+"] ":"")... <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li>@Html.RouteLink("همه", "AdministrationList", new {Controller = "Contents", page = 1})</li>
                    <li>@Html.ActionLink("خبر", "List", new { contentType = "news", page = 1, recordPerPage })</li>
                    <li>@Html.ActionLink("رخداد", "List", new { contentType = "event", page = 1, recordPerPage })</li>
                    <li>@Html.ActionLink("تقویم", "List", new { contentType = "calendar", page = 1, recordPerPage })</li>
                    <li>@Html.ActionLink("صفحه", "List", new { contentType = "page", page = 1, recordPerPage })</li>
                    <li>@Html.ActionLink("لینک", "List", new { contentType = "link", page = 1, recordPerPage })</li>
                    <li>@Html.ActionLink("منو", "List", new { contentType = "menu", page = 1, recordPerPage })</li>
                </ul>
            </div>
            <div class="btn-group">
                <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">ثبت... <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li>@Html.ActionLink("خبر", "Create", new {contentType = "news"})</li>
                    <li>@Html.ActionLink("رخداد", "Create", new {contentType = "event"})</li>
                    <li>@Html.ActionLink("تقویم", "Create", new {contentType = "calendar"})</li>
                    <li>@Html.ActionLink("صفحه", "Create", new {contentType = "page"})</li>
                    <li>@Html.ActionLink("لینک", "Create", new {contentType = "link"})</li>
                    <li>@Html.ActionLink("منو", "Create", new {contentType = "menu"})</li>
                </ul>
            </div>
        </div>
        <hr />
        @{
            var error = TempData["Error"] as string;

            bool hasError = error != null;
        }
        @if (hasError)
        {
            <div class="validation-summary-errors">
                <ul>
                    <li>@error</li>
                </ul>
            </div>
        }
        @if (!Model.Any())
        {
            <p class="center">@ValidationResources.NoRecords</p>
        }
        else
        {
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(c => c.Title)
                    </th>
                    @if (!hasType || (type == ContentType.Pages || type == ContentType.Menu || type == ContentType.Links))
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.DisplayOrder)
                        </th>
                    }
                    @if (!hasType || type == ContentType.News)
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.IsHot)
                        </th>
                    }
                    @if (!hasType)
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.TypeInt)
                        </th>
                    }
                    @if (!hasType || (type == ContentType.News || type == ContentType.Events || type == ContentType.Calendars))
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.Rate)
                        </th>
                    }
                    @if (!hasType || (type == ContentType.Pages || type == ContentType.Links))
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.ParentId)
                        </th>
                    }
                    <th>
                        @Html.DisplayNameFor(c => c.AuthorId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(c => c.CategoryId)
                    </th>
                    @if (!hasType || (type == ContentType.News || type == ContentType.Events || type == ContentType.Calendars))
                    {
                        <th>
                            @Html.DisplayNameFor(c => c.Comments)
                        </th>
                    }
                    <th>
                        عملیات
                    </th>
                </tr>
                @foreach (Content content in Model)
                {
                    <tr>
                        <td>
                            @content.Title.EnsureLength(40)
                        </td>
                        @if (!hasType || (type == ContentType.Pages || type == ContentType.Menu || type == ContentType.Links))
                        {
                            <td>
                                @content.DisplayOrder
                            </td>
                        }
                        @if (!hasType || type == ContentType.News)
                        {
                            <td>
                                @(content.IsHot ? "بله" : "خیر")
                            </td>
                        }
                        @if (!hasType)
                    {
                            <td>
                                @content.Type.ToLocalizedString()
                            </td>
                        }
                        @if (!hasType || (type == ContentType.News || type == ContentType.Events || type == ContentType.Calendars))
                        {
                            <td>
                                @if (content.Rate <= 0)
                                {
                                    <text>بدون امتیاز</text>
                                }
                                else
                                {
                                    @Html.DisplayFor(trap => content.Rate)
                                }
                            </td>
                        }
                        @if (!hasType || (type == ContentType.Pages || type == ContentType.Links))
                        {
                            <td>
                                @helper ShowSubItems(Content content, bool setSeparator)
                                {
                                    if (content.Parent != null)
                                    {
                                        @ShowSubItems(content.Parent, true)
                                    }

                                    @Html.ActionLink(content.Title.EnsureLength(20), "Edit", new {content.Id})

                                    if (setSeparator)
                                    {
                                        <text>/</text>
                                    }
                                }
                                @if (content.Parent != null)
                                {
                                    @ShowSubItems(content.Parent, false)
                                }
                                else
                                {
                                    <div>ندارد</div>
                                }
                            </td>
                        }
                        <td>
                            @Html.ActionLink(content.Author.UserName.EnsureLength(10), "Edit", "Users", new {content.Author.Id}, null)
                        </td>
                        <td>
                            @if (content.Category != null)
                            {
                                @Html.ActionLink(content.Category.Title.EnsureLength(20), "Edit", "Categories", new {content.Category.Id}, null)
                            }
                            else
                            {
                                <text>ندارد</text>
                            }
                        </td>
                        @if (!hasType || (type == ContentType.News || type == ContentType.Events || type == ContentType.Calendars))
                        {
                            <td>
                                @if (content.Comments.Count == 0)
                                {
                                    <text>بدون نظر</text>
                                }
                                else
                                {
                                    @Html.ActionLink(content.Comments.Count.ToString(), "List", "Comments", new {ownerId = content.Id}, null)
                                }
                            </td>
                        }
                        <td class="btn-group">
                            @Html.ActionLink("ویرایش", "Edit", new {content.Id}, new {@class = "btn"})
                            @Html.ActionLink("حذف", "Delete", new RouteValueDictionary(new {content.Id}), new Dictionary<string, object> {{"class", "btn btn-danger"}, {"data-toggle", "modal"}, {"data-target", "#delete-modal"}, {"data-delete-handle", "true"}})
                            @Html.ActionLink(content.IsPublished ? "عدم انتشار" : "انتشار", "ChangePublication", new {content.Id}, new {@class = "btn"})
                        </td>
                    </tr>
                }
            </table>
            @Html.Partial("_DeleteConfirmationModal")
            @Html.RenderPager(Model as IPagination, page => Url.Action("List", new { page, recordPerPage }))
        }
        <div class="clearfix">
        </div>
        <div class="box-footer single">
            @Html.ActionLink("برگشت به پنل مدیریت", "Default", "Administration", null, new {@class = "btn"})
        </div>
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/Contents/_NewOrUpdate.cshtml
@using Iauq.Core.Domain
@using Iauq.Core.Extensions
@using Iauq.Information.Helpers
@model Iauq.Core.Domain.Content
@{
    var type = (ContentType)ViewBag.Type;
}

@Html.AntiForgeryToken()
@if (type == ContentType.News)
{
    <div class="control-group">
        @Html.LabelFor(c => c.IsHot, new { @class = "control-label" })
        <div class="controls">
            @Html.CheckBoxFor(c => c.IsHot, new { @class = "input-xlarge" })
            @Html.ValidationMessageFor(c => c.IsHot, null, new { @class = "help-inline" })
        </div>
    </div>
}
@if (type == ContentType.Pages)
{
    <div class="control-group">
        @Html.LabelFor(c => c.ShowNestedContents, new { @class = "control-label" })
        <div class="controls">
            @Html.CheckBoxFor(c => c.ShowNestedContents, new { @class = "input-xlarge" })
            @Html.ValidationMessageFor(c => c.ShowNestedContents, null, new { @class = "help-inline" })
        </div>
    </div>
}
@if (type == ContentType.Pages || type == ContentType.Menu || type == ContentType.Links)
{
    <div class="control-group">
        @Html.LabelFor(c => c.DisplayOrder, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(c => c.DisplayOrder, new { @class = "input-mini" })
            @Html.ValidationMessageFor(c => c.DisplayOrder, null, new { @class = "help-inline" })
        </div>
    </div>
}
<div class="control-group">
    @Html.LabelFor(c => c.Title, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBoxFor(c => c.Title, new { @class = "input-xlarge" })
        @Html.ValidationMessageFor(c => c.Title, null, new { @class = "help-inline" })
    </div>
</div>
@if (type == ContentType.Pages || type == ContentType.Menu || type == ContentType.News)
{
    <div class="control-group">
        @Html.LabelFor(c => c.Abstract, new { @class = "control-label" })
        <div class="controls">
            @Html.TextAreaFor(c => c.Abstract, 5, 50, new { @class = "input-xxlarge ckeditor" })
            @Html.ValidationMessageFor(c => c.Abstract, null, new { @class = "help-inline" })
        </div>
    </div>
}
@if (type != ContentType.Links)
{
    <div class="control-group">
        @Html.LabelFor(c => c.Body, new { @class = "control-label" })
        <div class="controls">
            @Html.TextAreaFor(c => c.Body, 20, 50, new { @class = "input-xxlarge ckeditor" })
            @Html.ValidationMessageFor(c => c.Body, null, new { @class = "help-inline" })
        </div>
    </div>
}
else
{
    <div class="control-group">
        <label class="control-label" for="Body">آدرس</label>
        <div class="controls">
            @Html.TextBoxFor(c => c.Body, new { @class = "input-xxlarge align-left" })
            @Html.ValidationMessageFor(c => c.Body, null, new { @class = "help-inline" })
        </div>
    </div>
}
@if (type == ContentType.Pages || type == ContentType.News || type == ContentType.Events)
{
    <div class="control-group">
        @Html.LabelFor(c => c.Tags, new { @class = "control-label" })
        <div class="controls">
            @Html.TextAreaFor(c => c.Tags, 2, 50, new { @class = "input-xxlarge" })
            @Html.ValidationMessageFor(c => c.Tags, null, new { @class = "help-inline" })
        </div>
    </div>
}
@if (type == ContentType.News || type == ContentType.Pages)
{
    @Html.EditorFor(c => c.Metadata)
}
<div class="control-group">
    @Html.LabelFor(c => c.CategoryId, new { @class = "control-label" })
    <div class="controls">
        @*@Html.DropDownListFor(c => c.CategoryId, (SelectList) ViewBag.Categories, new {@class = "input-large"})*@
        <select class="input-large" data-val="true" id="CategoryId" name="CategoryId">
            @if ((bool)ViewBag.UserIsUnlimited)
            {
                <option value="">هچکدام</option>
            }
            @foreach (Category category in (List<Category>)ViewBag.Categories)
            {
                <option @(category.Id == Model.CategoryId ? "selected=\"selected\"" : "") value="@category.Id">@ShowSubItems(category, false)</option>
            }
            @helper ShowSubItems(Category category, bool setSeparator)
            {
                if (category.Parent != null)
                {
                    @ShowSubItems(category.Parent, true)
                }

                @category.Title.EnsureLength(20)

                if (setSeparator)
                {
                    <text>/</text>
                }
            }
        </select>
        @Html.ValidationMessageFor(c => c.CategoryId, null, new { @class = "help-inline" })
    </div>
</div>
@if (type == ContentType.Pages || type == ContentType.Links)
{
    <div class="control-group">
        @Html.LabelFor(c => c.ParentId, new { @class = "control-label" })
        <div class="controls">
            @*@Html.DropDownListFor(c => c.ParentId, (SelectList) ViewBag.Parents, "", new {@class = "input-large"})*@
            <select class="input-xxlarge" data-val="true" id="ParentId" name="ParentId">
                <option value="">هچکدام</option>
                
                @{
    IEnumerable<Content> rootParents = ((List<Content>)ViewBag.Parents).Where(c => c.Parent == null);
                }
                
                @foreach (Content content in rootParents)
                {
                    @Render(content)
                }

                @helper Render(Content content)
                    {
                    <option @(content.Id == Model.ParentId ? "selected=\"selected\"" : "") value="@content.Id">@ShowSubItems(content, false)</option>

                    foreach (Content child in content.Childs)
                    {
                        @Render(child)
                    }
                }

                @helper ShowSubItems(Content content, bool setSeparator)
                    {
                        if (content.Parent != null)
                        {
                        @ShowSubItems(content.Parent, true)
                        }

                    @content.Title.EnsureLength(20)

                        if (setSeparator)
                        {
                        <text>/</text>
                    }
                }
            </select>
            @Html.ValidationMessageFor(c => c.ParentId, null, new { @class = "help-inline" })
        </div>
    </div>
}
@Html.Partial("_TemplatesModal")

<script src="@UrlResolver.Script("ckeditor")"> </script>