src/Iauq.Information/Areas/Administration/Models/FileManager/CreateDirectoryModel.cs
using Iauq.Information.Models;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class CreateDirectoryModel : CreateDirectoryModelBase
    {
        public string TargetUrl { get; set; }

        public EntryModel CurrentEntry { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/CreateDirectoryModelBase.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Iauq.Information.Areas.Administration.Helpers;
using Iauq.Information.Models;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public abstract class CreateDirectoryModelBase : ModelBase
    {
        [DisplayName("نام")]
        [Required(ErrorMessage = "ذکر نام ضروری است.")]
        [FileNameValidator]
        public string Name { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/EntryModel.cs
using System;
using System.ComponentModel;
using System.IO;
using System.Web;
using Iauq.Core.Utilities;
using Iauq.Information.Helpers;
using Iauq.Information.Models;
using StructureMap;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class EntryModel : ModelBase
    {
        public EntryModel(string urlOrPath, bool isUrl, bool processParent)
        {
            if(string.IsNullOrEmpty(urlOrPath))
                return;

            var webHelper = ObjectFactory.GetInstance<IWebHelper>();

            if (isUrl)
            {
                CurrentUrl = urlOrPath;
                CurrentPath = HttpContext.Current.Server.MapPath(urlOrPath);
            }
            else
            {
                CurrentUrl = webHelper.MapUrl(urlOrPath);
                CurrentPath = urlOrPath;
            }

            IsDirectory = Directory.Exists(CurrentPath);
            IsFile = File.Exists(CurrentPath);

            if (processParent)
            {
                DirectoryInfo parent = Directory.GetParent(CurrentPath);

                if (parent != null)
                {
                    string parentUrl = webHelper.MapUrl(parent.FullName);
                    if (parentUrl.StartsWith(Constants.CdnUrl))
                    {
                        ParentPath = parent.FullName;
                        ParentUrl = parentUrl;
                    }
                }
            }

            if (IsDirectory)
            {
                CreationTime = Directory.GetCreationTime(CurrentPath);
            }
            else
            {
                CreationTime = File.GetCreationTime(CurrentPath);
            }
        }

        public bool IsDirectory { get; set; }
        public bool IsFile { get; set; }

        public string CurrentUrl { get; set; }
        public string CurrentPath { get; set; }
        public string CurrentName { get; set; }

        public string ParentUrl { get; set; }
        public string ParentPath { get; set; }
        public string ParentName { get; set; }

        [DisplayName("تاریخ ایجاد")]
        public DateTime CreationTime { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/FilesModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Web;
using Iauq.Core.Utilities;
using Iauq.Information.Models;
using StructureMap;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class FileManagerModel : ModelBase
    {
        public FileManagerModel()
        {
            Entries = new List<EntryModel>();
        }

        public EntryModel CurrentEntry { get; set; }

        [DisplayName("مسیر/فایل‌های جاری")]
        public List<EntryModel> Entries { get; set; }

        public static string ExtractParent(string url)
        {
            string path = HttpContext.Current.Server.MapPath(url);

            var webHelper = ObjectFactory.GetInstance<IWebHelper>();

            DirectoryInfo parent = Directory.GetParent(path);
            return webHelper.MapUrl(parent.FullName);
        }

        public static string EnsureIsDirectoryOrExtractParent(string url)
        {
            string path = HttpContext.Current.Server.MapPath(url);

            var webHelper = ObjectFactory.GetInstance<IWebHelper>();

            if (Directory.Exists(path))
                return webHelper.MapUrl(path);

            DirectoryInfo parent = Directory.GetParent(path);
            return webHelper.MapUrl(parent.FullName);
        }

        public static string ExtractName(string url)
        {
            string path;
            if (Directory.Exists(url))
                path = url;
            else
                path = HttpContext.Current.Server.MapPath(url);

            if (Directory.Exists(path))
                return new DirectoryInfo(path).Name;

            return new FileInfo(path).Name;
        }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/RenameModel.cs
namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class RenameModel : RenameModelBase
    {
        public string TargetUrl { get; set; }

        public EntryModel CurrentEntry { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/RenameModelBase.cs
using System.ComponentModel;
using Iauq.Information.Areas.Administration.Helpers;
using Iauq.Information.Models;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class RenameModelBase : ModelBase
    {
        [DisplayName("نام فعلی")]
        public string OldName { get; set; }

        [DisplayName("نام جدید")]
        [FileNameValidator]
        public string NewName { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/UploadFileModel.cs
namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public class UploadFileModel : UploadFileModelBase
    {
        public string TargetUrl { get; set; }
        
        public EntryModel CurrentEntry { get; set; }
    }
}

src/Iauq.Information/Areas/Administration/Models/FileManager/UploadFileModelBase.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Iauq.Information.Areas.Administration.Helpers;
using Iauq.Information.Models;

namespace Iauq.Information.Areas.Administration.Models.FileManager
{
    public abstract class UploadFileModelBase : ModelBase
    {
        [DisplayName("نام")]
        [FileNameValidator]
        public string FileName { get; set; }

        [DisplayName("فایل")]
        [Required(ErrorMessage = "لطفا فایل مورد نظر را انتخاب کنید.")]
        public HttpPostedFileBase PostedFile { get; set; }

        public string ContentType
        {
            get
            {
                if (PostedFile == null)
                    return null;

                return PostedFile.ContentType;
            }
        }

        public int ContentLength
        {
            get
            {
                if (PostedFile == null)
                    return -1;

                return PostedFile.ContentLength;
            }
        }
    }
}

src/Iauq.Information/Areas/Administration/Controllers/FileManagerController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Iauq.Core.Utilities;
using Iauq.Information.App_GlobalResources;
using Iauq.Information.Areas.Administration.Models.FileManager;
using Iauq.Information.Helpers;
using Iauq.Information.LogProviders;

namespace Iauq.Information.Areas.Administration.Controllers
{
    [CustomAuthorize(Roles = "Administrators, Moderators")]
    public class FileManagerController : AdministrationControllerBase
    {
        private readonly IWebHelper _webHelper;

        public FileManagerController(IWebHelper webHelper)
        {
            _webHelper = webHelper;
        }

        public ActionResult List(string currentUrl)
        {
            currentUrl = "/" + currentUrl;

            if (currentUrl.Contains("..") ||
                !currentUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            string currentPath = Server.MapPath(currentUrl);

            if (!Directory.Exists(currentPath))
                return NotFoundView();

            bool processParent = currentUrl != Constants.CdnUrl;

            var model = new FileManagerModel {CurrentEntry = new EntryModel(currentUrl, true, processParent)};

            string[] entries = Directory.GetFileSystemEntries(currentPath);

            foreach (string entry in entries)
            {
                model.Entries.Add(new EntryModel(entry, false, false));
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Rename(string targetUrl)
        {
            targetUrl = "/" + targetUrl;

            if (targetUrl.Contains("..") ||
                !targetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            string targetPath = Server.MapPath(targetUrl);

            if ((!Directory.Exists(targetPath) && !System.IO.File.Exists(targetPath)))
                return NotFoundView();

            DirectoryInfo parent = Directory.GetParent(targetPath);
            string directoryOrFileName = targetPath.Substring(parent.FullName.Length + 1,
                                                              targetPath.Length - (parent.FullName.Length + 1));


            bool processParent = targetUrl != Constants.CdnUrl;

            return
                View(new RenameModel
                         {
                             TargetUrl = targetUrl,
                             OldName = directoryOrFileName,
                             CurrentEntry = new EntryModel(targetUrl, true, processParent)
                         });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Rename(RenameModel model)
        {
            model.TargetUrl = "/" + model.TargetUrl;

            bool processParent = model.TargetUrl != Constants.CdnUrl;

            model.CurrentEntry = new EntryModel(model.TargetUrl, true, processParent);

            if (model.TargetUrl.Contains("..") ||
                !model.TargetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ValidationResources.InvalidState);

                return View(model);
            }

            if (string.IsNullOrEmpty(model.NewName))
                return RedirectToAction("List",
                                        new
                                            {
                                                currentUrl =
                                            FileManagerModel.EnsureIsDirectoryOrExtractParent(model.TargetUrl)
                                            });


            if (Path.GetExtension(model.NewName) == "")
                model.NewName += Path.GetExtension(model.OldName);

            string targetPath = Server.MapPath(model.TargetUrl);

            DirectoryInfo parent = Directory.GetParent(targetPath);

            string newPath = Path.Combine(parent.FullName, model.NewName);

            if (string.Compare(targetPath, newPath, StringComparison.OrdinalIgnoreCase) == 0)
                return RedirectToAction("List", new {currentUrl = model.TargetUrl});

            if ((!Directory.Exists(targetPath) && !System.IO.File.Exists(targetPath)))
                return NotFoundView();

            bool isSaved;

            try
            {
                if (Directory.Exists(targetPath))
                {
                    Directory.Move(targetPath, newPath);
                }
                else
                {
                    System.IO.File.Move(targetPath, newPath);
                }

                isSaved = true;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
            {
                Logger.SaveLog(new RenameDirectoryOrFileProvider(model));
            }
            else
                TempData["Error"] = ValidationResources.RenameFailure;

            return RedirectToAction("List", new {currentUrl = _webHelper.MapUrl(parent.FullName)});
        }

        [HttpGet]
        public ActionResult CreateDirectory(string targetUrl)
        {
            targetUrl = "/" + targetUrl;

            if (targetUrl.Contains("..") ||
                !targetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            string targetPath = Server.MapPath(targetUrl);

            if ((!Directory.Exists(targetPath) && !System.IO.File.Exists(targetPath)))
                return NotFoundView();

            bool processParent = targetUrl != Constants.CdnUrl;

            return View(new CreateDirectoryModel
                            {
                                TargetUrl = targetUrl,
                                CurrentEntry = new EntryModel(targetUrl, true, processParent)
                            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDirectory(CreateDirectoryModel model)
        {
            model.TargetUrl = "/" + model.TargetUrl;

            bool processParent = model.TargetUrl != Constants.CdnUrl;

            model.CurrentEntry = new EntryModel(model.TargetUrl, true, processParent);

            if (model.TargetUrl.Contains("..") ||
                !model.TargetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ValidationResources.InvalidState);

                return View(model);
            }

            string targetPath = Server.MapPath(model.TargetUrl);

            string newPath = Path.Combine(targetPath, model.Name);

            if (Directory.Exists(newPath))
            {
                ModelState.AddModelError("", ValidationResources.DuplicateDirectoryName);

                return View(model);
            }

            bool isSaved;

            try
            {
                Directory.CreateDirectory(newPath);

                isSaved = true;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
            {
                Logger.SaveLog(new CreateDirectoryProvider(model));
            }
            else
                TempData["Error"] = ValidationResources.CreateDirectoryFailure;

            return RedirectToAction("List", new {currentUrl = _webHelper.MapUrl(newPath)});
        }

        [HttpGet]
        public ActionResult UploadFile(string targetUrl)
        {
            targetUrl = "/" + targetUrl;

            if (targetUrl.Contains("..") ||
                !targetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            string targetPath = Server.MapPath(targetUrl);

            if ((!Directory.Exists(targetPath) && !System.IO.File.Exists(targetPath)))
                return NotFoundView();

            bool processParent = targetUrl != Constants.CdnUrl;

            return View(new UploadFileModel
                            {
                                TargetUrl = targetUrl,
                                CurrentEntry = new EntryModel(targetUrl, true, processParent)
                            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadFile(UploadFileModel model)
        {
            model.TargetUrl = "/" + model.TargetUrl;

            bool processParent = model.TargetUrl != Constants.CdnUrl;

            model.CurrentEntry = new EntryModel(model.TargetUrl, true, processParent);

            if (model.TargetUrl.Contains("..") ||
                !model.TargetUrl.StartsWith(Constants.CdnUrl))
                return NotFoundView();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ValidationResources.InvalidState);

                return View(model);
            }

            if (string.IsNullOrWhiteSpace(model.FileName))
                model.FileName = model.PostedFile.FileName;

            string targetPath = Server.MapPath(model.TargetUrl);

            const string extensions =
                ".7z|.aiff|.asf|.avi|.bmp|.csv|.doc|.docx|.fla|.flv|.gif|.gz|.gzip|.jpeg|.jpg|.mid|.mov|.mp3|.mp4|.mpc|.mpeg|.mpg|.ods|.odt|.pdf|.png|.ppt|.pxd|.qt|.ram|.rar|.rm|.rmi|.rmvb|.rtf|.sdc|.sitd|.swf|.sxc|.sxw|.tar|.tgz|.tif|.tiff|.txt|.vsd|.wav|.wma|.wmv|.xls|.xml|.zip";

            if (Path.GetExtension(model.FileName) == "")
                model.FileName += Path.GetExtension(model.PostedFile.FileName);

            if (model.ContentLength == 0 ||
                extensions.Split('|').All(e => string.Compare(e, Path.GetExtension(model.FileName), StringComparison.OrdinalIgnoreCase) != 0))
            {
                ModelState.AddModelError("", ValidationResources.SelectedFileIsInvalid);

                return View(model);
            }

            bool isSaved;

src/Iauq.Information/Areas/Administration/Views/FileManager/CreateDirectory.cshtml
@using Iauq.Core.Utilities
@using Iauq.Information.Areas.Administration.Models.FileManager
@using Iauq.Information.Helpers
@using Iauq.Web.Mvc.UI
@using StructureMap
@model Iauq.Information.Areas.Administration.Models.FileManager.CreateDirectoryModel

@{
    ViewBag.Title = "پنل مدیریت - مدیریت فایل‌ها - ایجاد مسیر جدید";
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("مدیریت فایل‌ها", "List", "FileManager", new { currentUrl = Constants.CdnUrl }, null));
    
    var currentEntry = new EntryModel(new EntryModel(Model.CurrentEntry.CurrentUrl, true, true).CurrentUrl, true, true);
    var directories = new List<MvcHtmlString>();

    while (currentEntry.CurrentUrl != null)
    {
        directories.Add(@Html.ActionLink(FileManagerModel.ExtractName(currentEntry.CurrentUrl), "List", new { currentEntry.CurrentUrl }));

        currentEntry = new EntryModel(currentEntry.ParentUrl, true, true);
    }

    directories.Reverse();

    foreach (MvcHtmlString dir in directories)
    {
        PagePartManager.Current.AddBreadcrumb(dir);
    }
    
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("ایجاد مسیر جدید", "CreateDirectory", "FileManager", new {targetUrl = Model.TargetUrl}));
}

@Html.AntiForgeryToken()
<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr />
        @using (Html.BeginForm("CreateDirectory", "FileManager", new {Model.TargetUrl}, FormMethod.Post, new {@class = "form-horizontal"}))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <div class="control-group">
                    @Html.LabelFor(cdm => cdm.Name, new {@class = "control-label"})
                    <div class="controls">
                        @Html.TextBoxFor(cdm => cdm.Name, new {@class = "input-large"})
                        @Html.ValidationMessageFor(cdm => cdm.Name, null, new {@class = "help-inline"})
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">ایجاد مسیر</button>
                    @Html.ActionLink("برگشت", "List", new { currentUrl = ObjectFactory.GetInstance<IWebHelper>().MapUrl(FileManagerModel.EnsureIsDirectoryOrExtractParent(Model.TargetUrl)) }, new { @class = "btn" })
                </div>
            </fieldset>
        }
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/FileManager/List.cshtml
@using Iauq.Core.Extensions
@using Iauq.Information.App_GlobalResources
@using Iauq.Information.Areas.Administration.Models.FileManager
@using Iauq.Information.Helpers
@using Iauq.Web.Mvc.UI
@model Iauq.Information.Areas.Administration.Models.FileManager.FileManagerModel
@{
    ViewBag.Title = "پنل مدیریت - مدیریت فایل‌ها";
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("مدیریت فایل‌ها", "List", "FileManager", new { currentUrl=Constants.CdnUrl }, null));

    var currentEntry = new EntryModel(new EntryModel(Model.CurrentEntry.CurrentUrl, true, true).CurrentUrl, true, true);
    var directories = new List<MvcHtmlString>();

    while (currentEntry.CurrentUrl != null)
    {
        directories.Add(@Html.ActionLink(FileManagerModel.ExtractName(currentEntry.CurrentUrl), "List", new {currentEntry.CurrentUrl}));

        currentEntry = new EntryModel(currentEntry.ParentUrl, true, true);
    }

    directories.Reverse();

    foreach (MvcHtmlString dir in directories)
    {
        PagePartManager.Current.AddBreadcrumb(dir);
    }
}
<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <div class="btn-toolbar ignore-heading pull-left">
            <div class="btn-group">
                @if (!string.IsNullOrEmpty(Model.CurrentEntry.ParentUrl) && Model.CurrentEntry.ParentUrl != Model.CurrentEntry.CurrentUrl)
                {
                    @Html.ActionLink("تغییر نام", "Rename", new {targetUrl = Model.CurrentEntry.CurrentUrl}, new {@class = "btn"})
                    @Html.ActionLink("حذف", "Delete", new RouteValueDictionary(new {targetUrl = Model.CurrentEntry.CurrentUrl}), new Dictionary<string, object> {{"class", "btn btn-danger"}, {"data-toggle", "modal"}, {"data-target", "#delete-modal"}, {"data-delete-handle", "true"}})
                    @Html.ActionLink("برگشت", "List", new {currentUrl = Model.CurrentEntry.ParentUrl}, new {@class = "btn"})
                }
            </div>
            <div class="btn-group">
                <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">... <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li>@Html.ActionLink("ایجاد پوشه", "CreateDirectory", new {targetUrl = Model.CurrentEntry.CurrentUrl})</li>
                    <li>@Html.ActionLink("ارسال فایل", "UploadFile", new {targetUrl = Model.CurrentEntry.CurrentUrl})</li>
                </ul>
            </div>
        </div>
        <hr />
        @{
            var error = TempData["Error"] as string;

            bool hasError = error != null;
        }
        @if (hasError)
        {
            <div class="validation-summary-errors">
                <ul>
                    <li>@error</li>
                </ul>
            </div>
            <hr/>
        }
        @if (!Model.Entries.Any())
        {
            <p class="center">@ValidationResources.NoDirectoryOrFiles</p>
        }
        else
        {
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(c => c.Entries)
                    </th>
                    <th>
                        عملیات
                    </th>
                </tr>
                @foreach (EntryModel entry in Model.Entries.OrderByDescending(e => e.IsDirectory).ThenBy(e => e.CurrentUrl))
                {
                    <tr>
                        <td class="align-left">
                            <h3>
                                @if (entry.IsDirectory)
                                {
                                    @Html.ActionLink(FileManagerModel.ExtractName(entry.CurrentUrl), "List", new {entry.CurrentUrl}, new {@class = "pull-right"})
                                }
                                else
                                {
                                    <a href="@entry.CurrentUrl" class="pull-right" target="_blank">@FileManagerModel.ExtractName(entry.CurrentUrl)</a>
                                }
                                <span>
                                    @Html.DisplayNameFor(c => c.CurrentEntry.CreationTime): @entry.CreationTime.ToPersianDate()
                                </span>
                            </h3>
                        </td>
                        <td class="btn-group">
                            @Html.ActionLink("تغییر نام", "Rename", new {targetUrl = entry.CurrentUrl}, new {@class = "btn"})
                            @Html.ActionLink("حذف", "Delete", new RouteValueDictionary(new {targetUrl = entry.CurrentUrl}), new Dictionary<string, object> {{"class", "btn btn-danger"}, {"data-toggle", "modal"}, {"data-target", "#delete-modal"}, {"data-delete-handle", "true"}})
                        </td>
                    </tr>
                }
            </table>
        }
        @Html.Partial("_DeleteConfirmationModalForDirectoryOrFile")
        <div class="clearfix">
        </div>
        <div class="box-footer single">
            @Html.ActionLink("برگشت به پنل مدیریت", "Default", "Administration", null, new {@class = "btn"})
        </div>
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/FileManager/Rename.cshtml
@using Iauq.Core.Utilities
@using Iauq.Information.Areas.Administration.Models.FileManager
@using Iauq.Information.Helpers
@using Iauq.Web.Mvc.UI
@using StructureMap
@model Iauq.Information.Areas.Administration.Models.FileManager.RenameModel

@{
    ViewBag.Title = string.Format("پنل مدیریت - مدیریت فایل‌ها - تغییر نام: {0}", Model.OldName);
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("مدیریت فایل‌ها", "List", "FileManager", new { currentUrl = Constants.CdnUrl }, null));

    var currentEntry = new EntryModel(new EntryModel(Model.CurrentEntry.CurrentUrl, true, true).CurrentUrl, true, true);
    var directories = new List<MvcHtmlString>();

    while (currentEntry.CurrentUrl != null)
    {
        directories.Add(@Html.ActionLink(FileManagerModel.ExtractName(currentEntry.CurrentUrl), "List", new { currentEntry.CurrentUrl }));

        currentEntry = new EntryModel(currentEntry.ParentUrl, true, true);
    }

    directories.Reverse();

    foreach (MvcHtmlString dir in directories)
    {
        PagePartManager.Current.AddBreadcrumb(dir);
    }
    
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink(string.Format("تغییر نام: {0}", Model.OldName), "Rename", "FileManager", new {targetUrl = Model.TargetUrl}));
}

@Html.AntiForgeryToken()
<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr />
        @using (Html.BeginForm("Rename", "FileManager", new {Model.TargetUrl}, FormMethod.Post, new {@class = "form-horizontal"}))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <div class="control-group">
                    @Html.LabelFor(rm => rm.OldName, new {@class = "control-label"})
                    <div class="controls">
                        @Html.TextBoxFor(rm => rm.OldName, new {@class = "input-large", @readonly = "true"})
                    </div>
                </div>
                <div class="control-group">
                    @Html.LabelFor(rm => rm.NewName, new {@class = "control-label"})
                    <div class="controls">
                        @Html.TextBoxFor(rm => rm.NewName, new {@class = "input-large"})
                        @Html.ValidationMessageFor(rm => rm.NewName, null, new {@class = "help-inline"})
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">تغییر نام</button>
                    @Html.ActionLink("برگشت", "List", new {currentUrl = ObjectFactory.GetInstance<IWebHelper>().MapUrl(FileManagerModel.EnsureIsDirectoryOrExtractParent(Model.TargetUrl))}, new {@class = "btn"})
                </div>
            </fieldset>
        }
    </div>
</div>