src/Iauq.Information/Areas/Administration/Controllers/CommentsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Iauq.Core.Domain;
using Iauq.Core.Utilities;
using Iauq.Data;
using Iauq.Data.Services;
using Iauq.Information.App_GlobalResources;
using Iauq.Information.Helpers;
using Iauq.Information.LogProviders;
using MvcContrib.Pagination;

namespace Iauq.Information.Areas.Administration.Controllers
{
    [CustomAuthorize(Roles = "Administrators, Moderators, Editors")]
    public class CommentsController : AdministrationControllerBase
    {
        private readonly ICategoryService _categoryService;
        private readonly ICommentService _commentService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHelper _webHelper;

        public CommentsController(IUnitOfWork unitOfWork, ICommentService commentService,
                                  ICategoryService categoryService, IWebHelper webHelper)
        {
            _unitOfWork = unitOfWork;
            _commentService = commentService;
            _categoryService = categoryService;
            _webHelper = webHelper;
        }

        [HttpGet]
        public ActionResult List(int? ownerId, int page = 1)
        {
            if (page < 1 || (ownerId.HasValue && ownerId < 1))
            {
                if (ownerId > 0)
                    return RedirectToActionPermanent("List", new {page = 1, ownerId});
                return RedirectToActionPermanent("List", new {page = 1});
            }

            IQueryable<Comment> query;

            if (ownerId.HasValue)
            {
                query = _commentService.GetAllCommentsByOwnerId(ownerId.Value).OrderBy(c => c.Id);
            }
            else
            {
                query = _commentService.GetAllComments().OrderBy(c => c.Id);
            }

            ExcludeNotRealatedRecords(ref query);

            var results =
                new LazyPagination<Comment>(query, page, Constants.RecordPerPage);

            if (!results.Any() && page != 1)
                return RedirectToActionPermanent("List", new {page = 1});

            ViewBag.OwnerId = ownerId;

            return ViewOrPartialView(results);
        }

        private bool UserIsUnlimited()
        {
            User user = _webHelper.GetCurrentUser(ControllerContext.HttpContext);

            if (_webHelper.IsInRole(user, "Administrators") || _webHelper.IsInRole(user, "Moderators"))
                return true;

            return false;
        }

        private IEnumerable<Category> GetUserCategories()
        {
            User user = _webHelper.GetCurrentUser(ControllerContext.HttpContext);

            List<Role> roles = user.Roles.ToList();

            List<int> categoryIds = roles.Where(r => r.Category != null).Select(r => r.Category.Id).ToList();

            return (from categories in _categoryService.GetAllCategories()
                    where categoryIds.Contains(categories.Id) || (categories.Parent != null &&
                                                                  categoryIds.Contains((int) categories.ParentId))
                    orderby categories.ParentId.HasValue ? categories.Parent.Title : categories.Title
                    select categories).ToList();
        }

        private void ExcludeNotRealatedRecords(ref IQueryable<Comment> query)
        {
            if (UserIsUnlimited())
                return;

            List<int> userCategories = GetUserCategories().Select(c => c.Id).ToList();

            query = from comments in query
                    where userCategories.Contains(comments.Owner.CategoryId ?? -1)
                    select comments;
        }

        [HttpGet]
        public ActionResult Create(int id)
        {
            var comment = new Comment();

            return ViewOrPartialView(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("",
                                         ValidationResources.InvalidState);

                return ViewOrPartialView(comment);
            }

            _commentService.SaveComment(comment);

            bool isSaved;

            try
            {
                isSaved = _unitOfWork.SaveChanges() > 0;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
                Logger.SaveLog(new CreateCommentProvider(comment));
            else
            {
                ModelState.AddModelError("", ValidationResources.CreationFailure);

                return ViewOrPartialView(comment);
            }

            if (IsReferrerValid())
                return Redirect(Request.UrlReferrer.AbsolutePath);

            return RedirectToAction("List", new {page = 1});
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Comment comment = _commentService.GetCommentById(id);

            if (comment == null)
                return EntityNotFoundView();

            return ViewOrPartialView(comment);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int id)
        {
            Comment dbComment = _commentService.GetCommentById(id);

            if (dbComment == null)
                return EntityNotFoundView();

            TryUpdateModel(dbComment, new[] {"Title", "Body"});

            if (!TryValidateModel(dbComment))
            {
                ModelState.AddModelError("",
                                         ValidationResources.InvalidState);

                return ViewOrPartialView(dbComment);
            }

            bool isSaved;

            try
            {
                isSaved = _unitOfWork.SaveChanges() > 0;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
                Logger.SaveLog(new UpdateCommentProvider(dbComment));
            else
            {
                ModelState.AddModelError("", ValidationResources.UpdateFailure);

                return ViewOrPartialView(dbComment);
            }

            if (IsReferrerValid())
                return Redirect(Request.UrlReferrer.AbsolutePath);

            return RedirectToAction("List", new {page = 1});
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Comment dbComment = _commentService.GetCommentById(id);

            if (dbComment == null)
                return EntityNotFoundView();

            _commentService.DeleteComment(dbComment);

            bool isSaved;

            try
            {
                isSaved = _unitOfWork.SaveChanges() > 0;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
                Logger.SaveLog(new DeleteCommentProvider(dbComment.Id));
            else
                TempData["Error"] = ValidationResources.DeleteFailure;

            if (IsReferrerValid())
                return Redirect(Request.UrlReferrer.AbsolutePath);

            return RedirectToAction("List", new {page = 1});
        }

        [HttpGet]
        public ActionResult ChangeApproval(int id)
        {
            Comment dbComment = _commentService.GetCommentById(id);

            if (dbComment == null)
                return EntityNotFoundView();

            dbComment.IsApproved = !dbComment.IsApproved;

            bool isSaved;

            try
            {
                isSaved = _unitOfWork.SaveChanges() > 0;
            }
            catch
            {
                isSaved = false;
            }

            if (isSaved)
                Logger.SaveLog(new CommentChangeApprovalProvider(dbComment));
            else
                TempData["Error"] = ValidationResources.UpdateFailure;

            if (IsReferrerValid())
                return Redirect(Request.UrlReferrer.AbsolutePath);

            return RedirectToAction("List", new {page = 1});
        }
    }
}

src/Iauq.Information/Areas/Administration/Views/Comments/Edit.cshtml
@using Iauq.Web.Mvc.UI
@model Iauq.Core.Domain.Comment

@{
    ViewBag.Title = string.Format("پنل مدیریت - نظرات - ویرایش نظر: {0}", Model.Title);
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("نظرات", "List", "Comments", new { page = 1 }, null));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink(string.Format("ویرایش نظر: {0}", Model.Title), "Edit", "Comments", new {Model.Id}));
}

<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr />
        @using (Html.BeginForm("Edit", "Comments", new {Model.Id}, FormMethod.Post, new {@class = "form-horizontal"}))
        {
            <input type="hidden" name="id" value="@Model.Id" />
            @Html.ValidationSummary(true)
            <fieldset>
                @{ Html.RenderPartial("_Update", Model); }
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">بروز رسانی</button>
                    @Html.ActionLink("برگشت", "List", new{page=1}, new {@class = "btn"})
                </div>
            </fieldset>
        }
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/Comments/List.cshtml
@using Iauq.Core.Domain
@using Iauq.Core.Extensions
@using MvcContrib.Pagination
@using Iauq.Information.App_GlobalResources
@using Iauq.Information.Helpers
@using Iauq.Web.Mvc.UI
@model IEnumerable<Iauq.Core.Domain.Comment>

@{
    ViewBag.Title = "پنل مدیریت - نظرات";
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("پنل مدیریت", "Default", "Administration"));
    PagePartManager.Current.AddBreadcrumb(Html.ActionLink("نظرات", "List", "Comments", new {page = 1}, null));
}

<div class="rounded-box newest row-fluid">
    <div class="inside">
        <h1>@ViewBag.Title
        </h1>
        <hr/>
        @{
            var error = TempData["Error"] as string;

            bool hasError = error != null;
        }
        @if (hasError)
        {
            <div class="validation-summary-errors">
                <ul>
                    <li>@error</li>
                </ul>
            </div>
        }
        @if (!Model.Any())
        {
            <p class="center">@ValidationResources.NoRecords</p>
        }
        else
        {
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(c => c.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(c => c.Owner)
                    </th>
                    <th>
                        @Html.DisplayNameFor(c => c.Parent)
                    </th>
                    <th>
                        @Html.DisplayNameFor(c => c.Commentor)
                    </th>
                    <th>
                        عملیات
                    </th>
                </tr>
                @foreach (Comment comment in Model)
                {
                    <tr>
                        <td>
                            @comment.Title.EnsureLength(40)
                        </td>
                        <td>
                            @Html.ActionLink(comment.Owner.Title.EnsureLength(30), "Edit", "Contents", new {comment.Owner.Id}, null)
                        </td>
                        <td>
                            @if (comment.Parent != null)
                            {
                                @Html.ActionLink(comment.Parent.Title.EnsureLength(30), "Edit", new {comment.Parent.Id})
                            }
                            else
                            {
                                <text>هیچکدام</text>
                            }
                        </td>
                        <td>
                            @if (comment.CommentorId.HasValue)
                            {
                                @Html.ActionLink(comment.Commentor.UserName.EnsureLength(20), "Edit", "Users", new {comment.Commentor.Id}, null)
                            }
                            else
                            {
                                @(comment.CommentorIp ?? "نامعلوم")
                            }
                        </td>
                        <td class="btn-group">
                            @Html.ActionLink("ویرایش", "Edit", new {comment.Id}, new {@class = "btn"})
                            @Html.ActionLink("حذف", "Delete", new RouteValueDictionary(new {comment.Id}), new Dictionary<string, object> {{"class", "btn btn-danger"}, {"data-toggle", "modal"}, {"data-target", "#delete-modal"}, {"data-delete-handle", "true"}})
                            @Html.ActionLink(comment.IsApproved ? "عدم تائید" : "تائید", "ChangeApproval", new {comment.Id}, new {@class = "btn"})
                        </td>
                    </tr>
                }
            </table>
            @Html.Partial("_DeleteConfirmationModal")
            if (ViewBag.OwnerId != null)
            {
                @Html.RenderPager(Model as IPagination, page => Url.Action("List", new {page, ViewBag.OwnerId}))
            }
            else
            {
                @Html.RenderPager(Model as IPagination, page => Url.Action("List", new {page}))
            }
        }
        <div class="clearfix"></div>
        <div class="box-footer single">
            @Html.ActionLink("برگشت به پنل مدیریت", "Default", "Administration", null, new {@class = "btn"})
        </div>
    </div>
</div>

src/Iauq.Information/Areas/Administration/Views/Comments/_Update.cshtml
@model Iauq.Core.Domain.Comment

@Html.AntiForgeryToken()
<div class="control-group">
    @Html.LabelFor(c => c.Title, new {@class = "control-label"})
    <div class="controls">
        @Html.TextBoxFor(c => c.Title, new {@class = "input-xxlarge"})
        @Html.ValidationMessageFor(c => c.Title, null, new {@class = "help-inline"})
    </div>
</div>
<div class="control-group">
    @Html.LabelFor(c => c.Body, new {@class = "control-label"})
    <div class="controls">
        @Html.TextAreaFor(c => c.Body,10,50, new {@class = "input-xxlarge"})
        @Html.ValidationMessageFor(c => c.Body, null, new {@class = "help-inline"})
    </div>
</div>